### PR TITLE
Encode single quote in directory path name

### PR DESCRIPTION
**Pull request by d-air1**
Well I took a stab at it. Took me a minute just to be able to read rust code, since I don't have any experience with rust. However, with just a couple line changes I did get it to work. Not sure if this is how you would have liked it to have been done though.

### CODE REVIEW

**Comment by d-air1** [comment]
This is about issue #1190

**Comment by svenstaro** [comment]
I'll merge after you fix the formatting issue.

**Comment by d-air1** [comment]
I'm assuming that running `cargo fmt` was the formatting issue you were speaking of? If so, I have just done so.

**Comment by d-air1** [comment]
I see that one of the CI tests failed and gave a useful error message, so I went ahead and made that change.

**Pull request merged**
