### PR TITLE
Add backslash to percent_encode_sets.PATH_SEGMENT

### LINKED ISSUE #545: Cannot retrieve file with \ in name
I was trying to reproduce a bug where files with `#` in the name wouldn't be served by an older version (that one seems fixed), and found that current master turns `\` into `/`.

I looked into the source a bit to find out why, remembered the whole set of problems with Paths and strings and `to_string_lossy` and promptly bailed. (Of course, it won't serve a file like `touch "$(echo 日本語 | iconv -f utf-8 -t shift-jis)"` either, and that's probably not easy to fix. I'm not sure that's common enough a problem to tackle.)

### PR DESCRIPTION
**Pull request by Jikstra**
Fixes #545

### CODE REVIEW

**Comment by svenstaro** [comment]
Any chance for a test? I think it should be trivial as you can probably just add an entry to the file fixtures with this name.

**Comment by Jikstra** [comment]
Oh yes! I somehow thought there was already a file with a backslash, but the backslash was just escaping another character ^^

**Comment by Jikstra** [comment]
Ay the test now fails on windows, i guess creating a file with a backslash on windows panics?

**Comment by aliemjay** [comment]
>  Is there some cool macro that we could add to that file so that it doesnt get created on windows?

`#[cfg(not(windows))]`

**Pull request merged**
