### PR TITLE
[Refactor] Miscellaneous small refactors

### PR DESCRIPTION
**Pull request by aliemjay**
Do they need separate PRs?

Please see individual commits.

Based on #529.

### CODE REVIEW

**Comment by aliemjay** [comment]
@svenstaro these are now REALLY small :)

**Review by svenstaro — APPROVED** [review]
Noice.

**Comment by svenstaro** [comment]
Got more refactors coming in building on top of this?

**Comment by aliemjay** [comment]
> Got more refactors coming in building on top of this?

Not for now :)

**Pull request merged**
