### PR TITLE
Show "now" when last modification time less than 11 seconds

### PR DESCRIPTION
**Pull request by KevCui**
Fix Issue #372 Tiny typo "now ago"

According to chrono-humanize `rough` period of accuracy, from 0 to 10 seconds duration, the text "now" is used https://gitlab.com/imp/chrono-humanize-rs/-/blob/master/src/humantime.rs#L173 and then followed by "ago" because of `past` tense https://gitlab.com/imp/chrono-humanize-rs/-/blob/master/src/humantime.rs#L141, which cause the tiny typo "now ago".

After the changes in this PR, if last modification time is less than 11 seconds, only "now" will show up.

### CODE REVIEW

**Comment by svenstaro** [comment]
Can you make clippy happy?

**Comment by KevCui** [comment]
clippy should be happy now. :smile:

**Comment by svenstaro** [comment]
Thanks! I was about to merge this and then I thought: Perhaps this is actually a better fix to put into humantime? Could you check into that real quick and see what upstream has to say about this? If they refuse for some reason, we can still merge it hear but I believe this is a general humantime problem.

**Comment by KevCui** [comment]
You're right. I thought the same thing.

I'll try to quickly contact the author of `chrono-humanize-rs` on gitlab. However, judging by the date of its latest commit, I'm afraid that the reply/fix in the upstream would take some time. Meanwhile, I'd suggest to merge the fix here in miniserve. If I got the the fix done in upstream in the future, I'll come back here and revert this change in miniserve.

Anyway, you're the better one to decide whether to merge the PR or not. I'll leave the decision to you. :)

**Comment by KevCui** [comment]
fyi, opened an issue in `chrono-humanize-rs` https://gitlab.com/imp/chrono-humanize-rs/-/issues/7

**Comment by svenstaro** [comment]
Let's let this sit for a few days to give the author some time to reply. Please do nudge me if I still haven't merged this in a week.

Thanks for your efforts!

**Comment by imp** [comment]
As mentioned in the [chrono-humanize issue](https://gitlab.com/imp/chrono-humanize-rs/-/issues/7) - the expected usage is to print `Humantime` value directly instead of going through `to_text_en` - this will do the right thing for all possible values of the `Duration`

**Comment by KevCui** [comment]
Thanks @imp for the hint. I updated the commit to use `HumanTime` value directly instead of `HumanTime:to_text_en`. `HumanTime` handles duration as accuracy `rough` by default and treats negative duration value as `past` tense. As the result, it works well when duration is form 0 to -10 seconds, showing `now`.

**Comment by imp** [comment]
Took me some time to realize that your input is `std::time::SystemTime`. Once I did I went ahead and added

`impl Humanize for SystemTime` (much as that of the other types in `chrono`)

So now you can directly call it on `SystemTime` like this:
```
use chrono_humanize::Humanize;

fn humanize_systemtime(time: Option<SystemTime>) -> Option<String> {
    time.map(|time| time.humanize())
}
```

* requires `chrono-humanize` >= 0.1.1

**Comment by svenstaro** [comment]
Thanks a lot @imp! @KevCui I updated to `chrono-humanize` 0.1.1 so you can now use it in this PR.

**Comment by KevCui** [comment]
Pretty handy, thanks for your support @imp :+1:

**Pull request merged**
