### PR TITLE
Combine ContextualError and ContextualErrorKind into one

### PR DESCRIPTION
**Pull request by KSXGitHub**
Close https://github.com/svenstaro/miniserve/issues/87

### CODE REVIEW

**Comment by boastful-squirrel** [comment]
Very cool 👍

**Comment by KSXGitHub** [comment]
It's settled then.

**Comment by boastful-squirrel** [comment]
Not yet, it's @svenstaro who decide :)

**Comment by svenstaro** [comment]
@boastful-squirrel You ok with this one?

**Comment by boastful-squirrel** [comment]
I am, on principle. I didn't have the occasion to test it but as long as we don't use contexts, this is probably the way we should handle errors, as it's equivalent feature-wise.

**Pull request merged**
