### PR TITLE
Split integration test into multiple files

### PR DESCRIPTION
**Pull request by KSXGitHub**
Fix https://github.com/svenstaro/miniserve/issues/85

**An additional issue arises:** `cargo test` warns me of unused items in helper module. This happens because the items are only used by test functions in test-only context. I don't know how to fix this other than `#[allow(dead_code)]`.

### CODE REVIEW

**Comment by svenstaro** [comment]
Can't you properly fix the warnings using cfg(test)? This way, the helper
stuff will only be compiled in test mode.

**Comment by KSXGitHub** [comment]
> Can't you properly fix the warnings using cfg(test)?

How exactly am I going to do this? I mean, if they are all in a single file, I can wrap them in a `#[cfg(test)] mod`, but they're scattered in multiple files.

**Comment by boastful-squirrel** [comment]
You can move the files into a subfolder of `tests`, call it `integration` or whatever you think is a good name. It should solve the unused code warnings.

**Comment by KSXGitHub** [comment]
@boastful-squirrel Your suggestion also hides dead code warnings, are you sure it is not `#[allow(dead_code)` with extra steps?

**Comment by svenstaro** [comment]
According to the [official guide](https://doc.rust-lang.org/book/ch11-03-test-organization.html#submodules-in-integration-tests), you're supposed to make it `tests/helpers/mod.rs` instead of `tests/helpers.rs`.

**Comment by svenstaro** [comment]
Also please call it `fixtures.rs` as `rstest` mimicks `pytest` and there it's common to call this sort of thing `fixtures`.

**Comment by KSXGitHub** [comment]
@svenstaro Is this what you suggested?

filesystem tree

Warnings didn't go anywhere:

terminal output

**Comment by svenstaro** [comment]
Looks exactly like https://github.com/rust-lang/rust/issues/46379

Putting it under `tests/fixtures/mod.rs` does have one benefit though: It makes cargo stop trying to run it as a test.

**Comment by svenstaro** [comment]
The workaround mentioned in the issue works btw but it _does_ hide real dead code. Overall I'm not happy with this and I'm not sure what the best solution would be.

**Comment by KSXGitHub** [comment]
> Putting it under `tests/fixtures/mod.rs` does have one benefit though: It makes cargo stop trying to run it as a test.

I believe not marking a function `#[test]` (or `#[rstest]`) makes cargo stop trying to run it as a test.

**Comment by KSXGitHub** [comment]
> I'm not sure what the best solution would be.

The best solution at the moment in my opinion is to `#[allow(dead_code)]`

**Comment by svenstaro** [comment]
> > Putting it under `tests/fixtures/mod.rs` does have one benefit though: It makes cargo stop trying to run it as a test.
> 
> I believe not marking a function `#[test]` (or `#[rstest]`) makes cargo stop trying to run it as a test.

True, but sadly it doesn't make cargo stop compiling the file. For that, you'll need to do the `mod.rs` trick.

I agree, for now, using `#[allow(dead_code)]` is the best choice. But please document why you use that somewhere in the file and maybe link the cargo bug report.

**Comment by KSXGitHub** [comment]
> True, but sadly it doesn't make cargo stop compiling the file. For that, you'll need to do the `mod.rs` trick.

Would writing a `#[test]` function in `mod.rs` disproves your claim? (I haven't try yet)

**Comment by KSXGitHub** [comment]
> > True, but sadly it doesn't make cargo stop compiling the file. For that, you'll need to do the `mod.rs` trick.
> 
> Would writing a `#[test]` function in `mod.rs` disproves your claim? (I haven't try it yet)

**Comment by svenstaro** [comment]
> 
> 
> > True, but sadly it doesn't make cargo stop compiling the file. For that, you'll need to do the `mod.rs` trick.
> 
> Would writing a `#[test]` function in `mod.rs` disproves your claim? (I haven't try it yet)

Well, it's not my claim, it's what's written in the docs. You can try, though. Let's get this merged.

**Comment by KSXGitHub** [comment]
> Let's get this merged.

Not yet.

**Comment by KSXGitHub** [comment]
I have made moved `helpers.rs` to `fixtures/mod.rs` for organizational purpose only, not for `cargo test` to ignore the file (it does not, I just tried it).

@svenstaro Please review

**Comment by svenstaro** [comment]
Actually putting stuff into `fixtures/mod.rs` does work exactly as expected. Compare the output of `cargo test`.

`cargo test` with `tests/fixtures.rs`:

```
test result: ok. 15 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/auth-f85dbcb4ad30be17

running 3 tests
test auth_works::case_3 ... ok
test auth_works::case_1 ... ok
test auth_works::case_2 ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/cli-13adc5119dab8f54

running 2 tests
test version_shows ... ok
test help_shows ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/fixtures-a0fdb7b285082d65

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/serve_request-86b061418b6f5951

running 2 tests
test serves_requests_with_no_options ... ok
test serves_requests_with_non_default_port ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/upload_files-b935706e952a427b

running 1 test
test uploading_files_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
`cargo test` with `tests/fixtures/mod.rs`:

```
test result: ok. 15 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/auth-f85dbcb4ad30be17

running 3 tests
test auth_works::case_2 ... ok
test auth_works::case_1 ... ok
test auth_works::case_3 ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/cli-13adc5119dab8f54

running 2 tests
test version_shows ... ok
test help_shows ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/serve_request-86b061418b6f5951

running 2 tests
test serves_requests_with_no_options ... ok
test serves_requests_with_non_default_port ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/upload_files-b935706e952a427b

running 1 test
test uploading_files_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Pull request merged**
