### PR TITLE
Add single click file icon to download file directly and change file …

### PR DESCRIPTION
**Pull request by chaibiq**
Add single click file icon to download file directly and change file size text of mobile view to no-wrap.

### CODE REVIEW

**Comment by svenstaro** [comment]
What's the reasoning behind this?

Also please fix the tests. :)

**Comment by chaibiq** [comment]
https://github.com/svenstaro/miniserve/actions/runs/8508049448
 Its already passed the tests , but here seeing 1 failing, 13 successful, 2 cancelled, and 1 skipped checks.
Dont know wrong in this page here..
Should I close it first ?

**Comment by svenstaro** [comment]
Well, do the tests work locally for you?

**Comment by chaibiq** [comment]
I already create new PR, but just update the scss part for mobile view.

I think to close this PR.

**Pull request closed without merging**
