### PR TITLE
Renders file listing using maud

### PR DESCRIPTION
**Pull request by boastful-squirrel**
So, this is my WIP using `maud`.

Feature-wise, this is equivalent to `master`. I was thinking, should I load the CSS from an external file in the `css()` method ? Or is the big string fine ? Anyways, I think you were right about using `maud`: it's amazingly fast (I tried to render a very huge directory, it did render in a blink) , and I think the code became less complex than before.

### CODE REVIEW

**Comment by svenstaro** [comment]
Not a thorough review but keep in mind to also change .travis-ci.yml to only use nightly and set the stable and beta to allow failure.

**Comment by svenstaro** [comment]
The css is fine the way it is. Maybe at some point I'll get annoyed and move it but for now let's keep it.

**Comment by boastful-squirrel** [comment]
I'll do it asap. I don't know Travis so I will take a look at the syntax before doing anything.

Gotcha for the css ;)

**Comment by boastful-squirrel** [comment]
I took the liberty to modify `convert_utc` and `humanize_systemtime`, so that if `None` is given as their parameter, it returns `None` instead of empty strings. `maud` allows the `if let` syntax, so there was no reason to return empty strings anymore. 

Also, I hope I didn't mess with the `travis.yml` file...

**Comment by svenstaro** [comment]
From the looks of it you need to explicitly tell travis to use nightly in the include matrix thing.

**Comment by boastful-squirrel** [comment]
It seems 6aff9bc fixed it

**Comment by svenstaro** [comment]
Well, you still have to do what I said because otherwise the release builds will be done using stable which is travis default as opposed to nightly.

**Comment by boastful-squirrel** [comment]
I hope this builds the matrix as expected. Otherwise, I could write this:
```
- rust: nightly
  env:
      - TARGET=x86_64-unknown-linux-musl
      - BIN_NAME=miniserve
      - PROPER_NAME=miniserve-linux
  os: linux
- rust: nightly
   env:
       - TARGET=x86_64-pc-windows-gnu
       - BIN_NAME=miniserve.exe
       - PROPER_NAME=miniserve-win.exe
       - RUSTFLAGS="-C linker=x86_64-w64-mingw32-gcc"
  os: linux
[...]
```

I hope both notations are equivalent...

**Comment by svenstaro** [comment]
What you did last doesn't work. What you wrote in the comment should work.

**Comment by boastful-squirrel** [comment]
OK cool ! Heading to #37 :)

**Comment by svenstaro** [comment]
Merging. Good job.

**Pull request merged**
