### PR TITLE
Multiple user accounts

### PR DESCRIPTION
**Pull request by KSXGitHub**
Fix https://github.com/svenstaro/miniserve/issues/100
Close https://github.com/svenstaro/miniserve/pull/118

**TODO:**
  - [ ] Add test
  - [x] ~~Add `ContextualError` to support multiple errors at once~~

### CODE REVIEW

**Comment by boastful-squirrel** [comment]
If @svenstaro validates that this is a useful feature, I think the implementation can be more simple. In particular, I'm pretty sure you could setup `StructOpt` so it takes a `Vec` of `RequiredAuth`, just like we do for the interfaces. Then, you would just have to adapt the middleware so that if at least 1 authentication succeeds, then it's fine.

**Comment by KSXGitHub** [comment]
> I'm pretty sure you could setup `StructOpt` so it takes a `Vec` of `RequiredAuth`

I had considered this too, but the time it takes increase as number of users increases (aka O(n) complexity), so I chose to use `HashMap` which has constant time evaluation.

**Comment by svenstaro** [comment]
I believe that for any number of users miniserve will ever handle, we don't
have to worry about complexity even if it were O(n!) :)

**Comment by KSXGitHub** [comment]
> I believe that for any number of users miniserve will ever handle

The user will decide how many accounts they need. I don't want to prevent them from doing what they want.

I have to admit that a linear list of `RequiredAuth` is easier to implement, but it will also lead to some interesting consequences:
  * It would be possible for a username to have more than one password.
  * It would compare two strings for each user, as opposed to comparing two hashed key (which is, by default, [a pair of two `u64`s](https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#3139-3142)). This would make the use of `Vec<RequiredAuth>` even more expensive.

**Comment by boastful-squirrel** [comment]
Admitting that would be useful (I don't think so, I like the mini part of miniserve), then reading accounts from a file or from a DB would be far more suitable. If we're talking about so much accounts that complexity matters, I wouldn't like to be the guy who has to type the command to start miniserve.

**Comment by KSXGitHub** [comment]
> then reading accounts from a file or from a DB would be far more suitable

Well, I made [this request](https://github.com/svenstaro/miniserve/issues/101)

**Comment by boastful-squirrel** [comment]
Note that according to the spec, an HTTP basic authentication password can contain any characters, which includes spaces and `:`.

For instance, `foo:bar xxx:yyy` should be read as `{user: "foo", password: "bar xxx:yyy"}`

**Comment by KSXGitHub** [comment]
> oh, it seems it doesn't work on `master` anymore. That's probably a regression caused by the handling of hashed passwords.

A necessary evil I think. We can still support escape characters though, but that would make the code more convoluted.

> Handling it through `StructOpt` is probably your only option.

I will try. But I'll still convert it into `HashMap` until I see a good reason not to.

**Comment by KSXGitHub** [comment]
@boastful-squirrel Wait a minute, I don't understand how `StructOpt` is going to solve the problem you described, which in my opinion is more of a parser problem (`parse_auth`).

**Comment by boastful-squirrel** [comment]
If `--auth` takes a `Vec<RequiredAuth>` with `number_of_values=1`, just like the interfaces, you should be able to write something like this: `miniserve -a xxx:yyy -a foo:bar -a bar:baz`. The `parse_auth()` method won't have to be changed since it will be applied to each of those credentials individually. The middleware will require some modifications though.

**Comment by KSXGitHub** [comment]
@boastful-squirrel So you want [this](https://github.com/svenstaro/miniserve/pull/118)?

**Pull request closed without merging**
