### PR TITLE
Use Clippy

### PR DESCRIPTION
**Pull request by KSXGitHub**
Fix https://github.com/svenstaro/miniserve/issues/93

**TODO:**
- [x] Wait for Travis CI to fail
- [x] Fix the code to satisfy clippy

### CODE REVIEW

**Comment by KSXGitHub** [comment]
So I ignored all of Clippy lint messages for one reason or another.

---

<pre><font color="#FBE84F"><b>warning</b></font><b>: writing `&amp;Vec&lt;_&gt;` instead of `&amp;[_]` involves one more reference and cannot be used with non-Vec-based slices.</b>
  <font color="#729ECF"><b>--&gt; </b></font>src/auth.rs:78:56
   <font color="#729ECF"><b>|</b></font>
<font color="#729ECF"><b>78</b></font> <font color="#729ECF"><b>| </b></font>pub fn compare_hash&lt;T: Digest&gt;(password: String, hash: &amp;Vec&lt;u8&gt;) -&gt; bool {
   <font color="#729ECF"><b>| </b></font>                                                       <font color="#FBE84F"><b>^^^^^^^^</b></font> <font color="#FBE84F"><b>help: change this to: `&amp;[u8]`</b></font>
   <font color="#729ECF"><b>|</b></font>
   <font color="#729ECF"><b>= </b></font><b>note</b>: #[warn(clippy::ptr_arg)] on by default
   <font color="#729ECF"><b>= </b></font><b>help</b>: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg

</pre>

I ignored this one because the suggested fix is unnecessarily complicated. I could've done it better, though, by using `GenericArray`, but that's for another pull request.

---

<pre><font color="#FBE84F"><b>warning</b></font><b>: identical conversion</b>
   <font color="#729ECF"><b>--&gt; </b></font>src/listing.rs:159:18
    <font color="#729ECF"><b>|</b></font>
<font color="#729ECF"><b>159</b></font> <font color="#729ECF"><b>| </b></font>    for entry in dir.path.read_dir()? {
    <font color="#729ECF"><b>| </b></font>                 <font color="#FBE84F"><b>^^^^^^^^^^^^^^^^^^^^</b></font> <font color="#FBE84F"><b>help: consider removing `dir.path.read_dir()?()`: `dir.path.read_dir()?`</b></font>
    <font color="#729ECF"><b>|</b></font>
    <font color="#729ECF"><b>= </b></font><b>note</b>: #[warn(clippy::identity_conversion)] on by default
    <font color="#729ECF"><b>= </b></font><b>help</b>: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#identity_conversion

</pre>

This one is ignored because I don't know what the hell Clippy is talking about.

---

<pre><font color="#FBE84F"><b>warning</b></font><b>: this function has too many arguments (11/7)</b>
  <font color="#729ECF"><b>--&gt; </b></font>src/renderer.rs:12:1
   <font color="#729ECF"><b>|</b></font>
<font color="#729ECF"><b>12</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>/</b></font> pub fn page(
<font color="#729ECF"><b>13</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>     serve_path: &amp;str,
<font color="#729ECF"><b>14</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>     entries: Vec&lt;Entry&gt;,
<font color="#729ECF"><b>15</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>     is_root: bool,
<font color="#729ECF"><b>...</b></font>  <font color="#FBE84F"><b>|</b></font>
<font color="#729ECF"><b>86</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>     }
<font color="#729ECF"><b>87</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font> }
   <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|_^</b></font>
   <font color="#729ECF"><b>|</b></font>
   <font color="#729ECF"><b>= </b></font><b>note</b>: #[warn(clippy::too_many_arguments)] on by default
   <font color="#729ECF"><b>= </b></font><b>help</b>: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#too_many_arguments

</pre>

This should be relatively easy to fix (use a `struct`), but this pull request does not concern with changing function signature.

---

<pre><font color="#FBE84F"><b>warning</b></font><b>: in an &apos;if&apos; condition, avoid complex blocks or closures with blocks; instead, move the block or closure higher and bind it with a &apos;let&apos;</b>
  <font color="#729ECF"><b>--&gt; </b></font>src/main.rs:86:26
   <font color="#729ECF"><b>|</b></font>
<font color="#729ECF"><b>86</b></font> <font color="#729ECF"><b>| </b></font>              .map_err(|e| {
   <font color="#729ECF"><b>| </b></font> <font color="#FBE84F"><b>__________________________^</b></font>
<font color="#729ECF"><b>87</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>                 ContextualError::IOError(
<font color="#729ECF"><b>88</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>                     &quot;Failed to retrieve symlink&apos;s metadata&quot;.to_string(),
<font color="#729ECF"><b>89</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>                     e,
<font color="#729ECF"><b>90</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>                 )
<font color="#729ECF"><b>91</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>             })?
   <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|_____________^</b></font>
   <font color="#729ECF"><b>|</b></font>
   <font color="#729ECF"><b>= </b></font><b>note</b>: #[warn(clippy::block_in_if_condition_stmt)] on by default
   <font color="#729ECF"><b>= </b></font><b>help</b>: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#block_in_if_condition_stmt

</pre>

My knowledge is insufficient.

**Comment by boastful-squirrel** [comment]
For the first one, I fixed it in my current PR, it's not merged yet. My PR has nothing to do with it but since I use Clippy, I decided to correct the error. For the last one, you just need to remove the curly brackets.

**Comment by KSXGitHub** [comment]
@boastful-squirrel Thanks.

**Comment by boastful-squirrel** [comment]
For the first one, if you want to fix it in this PR (because it should be in this PR rather than on mine), you can do what I did, see here: 
https://github.com/svenstaro/miniserve/commit/c2ce5295eb27610734ed539d47979c7bc0f0953b

**Comment by KSXGitHub** [comment]
@boastful-squirrel This PR only concern with linter. You can keep the fix in your PR.

**Comment by svenstaro** [comment]
This might sometimes break since [clippy isn't available in every nightly](https://rust-lang.github.io/rustup-components-history/). We can't really do anything proper against that short of fixing the nightly version or using clippy stable only. What do you think about using clippy stable only?

Advantage: Will likely always be available.
Disadvantage: Might not support experimental language constructs.

Keeping it like it is right now might randomly break builds.

**Comment by KSXGitHub** [comment]
@svenstaro 

How about this: I'm going to add Clippy in stable that does not allow failure, and change night one to allow failure.

**Comment by svenstaro** [comment]
Ok, sounds fair to me. Doesn't add too much complexity from what I can see.

**Comment by svenstaro** [comment]
Seems to be the wrong way around right now. Currently, stable may fail and nightly may not.

**Comment by KSXGitHub** [comment]
@svenstaro I'm not too familiar with Travis CI

**Comment by KSXGitHub** [comment]
@svenstaro I believe the last commit works, can you cancel the previous builds please?

**Comment by svenstaro** [comment]
Doesn't look correct I'm afraid. I also always struggle with travis.

**Comment by KSXGitHub** [comment]
Okay, I'm going to revert the changes. Are you OK with that?

**Comment by svenstaro** [comment]
Well, whatever it takes to make it work :)

To be honest, for now I'd roll with using only stable clippy and see how it goes.

**Comment by KSXGitHub** [comment]
@svenstaro Since you only want to use Clippy on Stable, I have 2 proposals:

1. Stop compiling `stable` and `beta` (since they don't compile anyway), and removing them from `allow_failures`, and add Clippy on `stable`.

2. Pin exact nightly version where Clippy is available (e.g. `nightly-2019-04-25`) [[more]](https://rust-lang.github.io/rustup-components-history/)

**Comment by svenstaro** [comment]
This is really a bit of a pinch since if we fix the exact version for clippy it means it will also sometimes randomly fail if the compiler changes and then the libs change to accommodate for the upstream rustc changes but then clippy will remain broken (as it's only compatible with the old version of the libs).

Ok, let's be naive about this and see how it goes. Let's only add a single clippy unstable target and if it fails too often we'll do something about it.

**Comment by KSXGitHub** [comment]
> Let's only add a single clippy unstable target and if it fails too often we'll do something about it.

So, you chose proposal 2 (Pin exact nightly version where Clippy is available)

**Comment by KSXGitHub** [comment]
BTW, I do have a few question though: Why must CI always use the latest nightly? Instead of pinning a particular nightly version that offers enough features you need?

**Comment by svenstaro** [comment]
Well, we could theoretically pin a version but I like being able to roll with the newest nightly to make sure that developers don't need to have a specific version that works.

Also, I'm not saying pin clippy, I'm saying let's keep it rolling and see how often it breaks.

**Comment by KSXGitHub** [comment]
According to [this table](https://rust-lang.github.io/rustup-components-history/), Clippy does not always present. My prediction is it will break very often.

**Comment by KSXGitHub** [comment]
So I have reverted the changes. And I am going to make another pull request regarding CI configuration.

**Comment by svenstaro** [comment]
If it turns out you're right and it breaks too often after all, we'll switch to a pinned version. Deal?

**Comment by svenstaro** [comment]
Sure.

**Pull request closed without merging**
