### PR TITLE
Add zip download functionality for windows users

### PR DESCRIPTION
**Pull request by marawan31**
This is quite simple, adding the ability to download folders as zip files instead of the alternatives.
This is mainly to help windows users download directories without the need to also install 7z or a similar app.

### CODE REVIEW

**Comment by svenstaro** [comment]
Thank you for the PR! Looks really neat. One important thing though: This doesn't seem to do streaming and so the browser can't start downloading the zip befor e it is entirely done zipping. This is in contrast to how our `.tar.gz` download behaves. Could you try to convert it to be streaming?

**Comment by marawan31** [comment]
This is hard to do because of the ZIP file format itself. The library used here uses the seek trait (because of the zip limitation i mentioned) to be able to modify the file, so streaming will not work with this.

**Comment by svenstaro** [comment]
Hm I did some research and I'll have to concede that you are correct. Still, the implications aren't great as from my understanding, you can potentially kill the service this way by zipping a large directory. I do see the convenience of zip for some users, though.

How about as a compromise, we document this problem with the zip archive somewhere user-visible and default to archiving-off by default and then add `--enable-zip` and `--enable-tar`? This seems sane and safe as a default.

**Comment by marawan31** [comment]
Yes, too large of a file can break the service and cause issues. How about using a temporary file that gets automatically deleted using the tempfile crate (only for zip)?

**Comment by svenstaro** [comment]
A temporary file can cause issues as well. I think I'd prefer it the way it is but change the archiving settings to be opt-in. Also document the problematic behavior of zip in the parameter help and then we're good.

**Comment by svenstaro** [comment]
Seems pretty good to me, thanks!

**Pull request merged**
