### PR TITLE
add a default index serving option (#156)

### PR DESCRIPTION
**Pull request by efx**
Start addressing #156 

~~Do you know where I should consume this option and how to configure active-web to serve the file? I started modifying [`fn configure_app(`](https://github.com/svenstaro/miniserve/blob/master/src/main.rs#L222) but couldn't figure out how to make it serve an `index.html` from within a configured directory root.~~

### CODE REVIEW

**Comment by efx** [comment]
After reading the documentation and codebase for a bit I figured it out. :)
The main things that remain are:
- allow configuring the name of the file `index.html`? Or simply let the user define the value instead of this being a boolean.
- `default-index` an ok name? It is shortened to `-d` which is confusing since it other utilities it means `daemon`.
- tests

**Comment by svenstaro** [comment]
Would probably be nice to be able to define its name with a proper default.

I don't think it should have a shorthand as it's a fairly "dangerous" option. Better not get the options mixed up. How about just `--index`?

**Comment by efx** [comment]
> I don't think it should have a shorthand as it's a fairly "dangerous" option. Better not get the options mixed up. How about just --index?
Good point. I'll update it to that and make it configurable with the default of `index.html`.

**Comment by svenstaro** [comment]
@efx Is this still WIP or shall I take a look?

**Comment by efx** [comment]
@svenstaro feel free to read through and give feedback.
The last thing I think it could use is adding a whitelist for the index file type.  In the current form it will serve up any file you pass. I've not tested with arbitrary files but it works well with `.html`.

**Comment by Lucretiel** [comment]
Status on this? I'd love to switch to miniserve as my default way of browsing `rustdoc` documentation

**Comment by efx** [comment]
@Lucretiel I have tested it locally serving other projects and it worked well. I have held back given it could use a bit more testing, but that is probably needless caution. 
So it just needs a good review. Happy to address anything you see; I'm a Rust beginner :smile: 
/cc @svenstaro

**Comment by Lucretiel** [comment]
I'd propose adding to the docstring:

```
/// The name of a directory ndex file to serve, like "index.html"
///
/// Normally, when miniserve serves a directory, it creates a listing for that directory.
/// However, If a directory contains this file, miniserve will serve that file instead.
```

**Comment by svenstaro** [comment]
Sorry for taking so incredibly long on this. I'll move it way up on my todo, promise!

**Comment by svenstaro** [comment]
Merged, thanks. And again sorry for taking so long. Will make a release with this soon-ish.

**Comment by efx** [comment]
> And again sorry for taking so long. Will make a release with this soon-ish.

I totally understand @svenstaro. Thank you for making this project!

**Comment by ngirard** [comment]
@efx, thanks for this pull request !
@svenstaro, thanks for this nice project ! A new release would indeed be great !

**Comment by svenstaro** [comment]
I want to make a release once the other PRs are in. Shouldn't take too much work to fix them up. :)

**Comment by ngirard** [comment]
Thanks for the release, @svenstaro !

**Comment by svenstaro** [comment]
Yeah, I decided that probably it's a good idea to just make a release now instead of waiting for too long.

**Pull request merged**
